import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { motion} from "motion/react"

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Mulah",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="scroll-smooth"> 
      <body className={`${workSans.className} antialiased w-full min-h-screen flex flex-col items-center overflow-x-hidden`}>
        <Navbar />
        <Toaster position="top-center" />
        <main className="w-full">
           {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
